# Generated by Django 5.1.2 on 2024-10-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='design',
            name='images',
        ),
        migrations.RemoveField(
            model_name='design',
            name='videos',
        ),
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saanj_app.category'),
        ),
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='designs/images/')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='saanj_app.design')),
            ],
        ),
        migrations.CreateModel(
            name='DesignMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(null=True, upload_to='design_media/')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='saanj_app.design')),
            ],
        ),
        migrations.CreateModel(
            name='DesignVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='designs/videos/')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='saanj_app.design')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saanj_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='subcategory1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory1'),
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory1')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='subcategory2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory2'),
        ),
        migrations.CreateModel(
            name='SubCategory3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory2')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='subcategory3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory3'),
        ),
    ]
