# Generated by Django 5.1.2 on 2024-10-18 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0002_rename_parent_category_category_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('In Manufacturing', 'In Manufacturing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], max_length=100)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saanj_app.design')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saanj_app.vendor')),
            ],
        ),
    ]
