# Generated by Django 5.1.2 on 2024-10-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0006_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='subcategory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory2'),
        ),
        migrations.AlterField(
            model_name='design',
            name='subcategory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saanj_app.subcategory3'),
        ),
        migrations.AlterField(
            model_name='designimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/images/'),
        ),
        migrations.AlterField(
            model_name='designmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='design_media/'),
        ),
        migrations.AlterField(
            model_name='designvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='designs/videos/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
