# Generated by Django 5.1.2 on 2024-10-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0008_vendor_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
