# Generated by Django 5.1.2 on 2024-10-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0009_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='active_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saanj_app.paymentpackage'),
        ),
    ]
