# Generated by Django 5.1.2 on 2024-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0011_package_remove_vendor_active_package_vendor_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
