# Generated by Django 5.1.2 on 2024-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0013_package_description_package_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
