# Generated by Django 5.1.2 on 2024-11-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0014_vendor_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
    ]
