# Generated by Django 5.1.2 on 2024-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0017_address_order_delete_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
