# Generated by Django 5.1.2 on 2024-11-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0021_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='placed', max_length=20),
        ),
    ]
