# Generated by Django 5.1.2 on 2024-11-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0024_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='saanj_app.package'),
        ),
    ]
