# Generated by Django 5.1.2 on 2024-11-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saanj_app', '0025_design_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
