# Generated by Django 5.1.2 on 2024-11-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='design',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='design',
            name='package',
        ),
        migrations.RemoveField(
            model_name='design',
            name='subcategory1',
        ),
        migrations.RemoveField(
            model_name='design',
            name='subcategory2',
        ),
        migrations.RemoveField(
            model_name='design',
            name='subcategory3',
        ),
        migrations.RemoveField(
            model_name='designmedia',
            name='design',
        ),
        migrations.RemoveField(
            model_name='designvideo',
            name='design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.RemoveField(
            model_name='designimage',
            name='design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='package',
        ),
        migrations.RemoveField(
            model_name='subcategory2',
            name='subcategory1',
        ),
        migrations.RemoveField(
            model_name='subcategory3',
            name='subcategory2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DesignMedia',
        ),
        migrations.DeleteModel(
            name='DesignVideo',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='DesignImage',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='SubCategory1',
        ),
        migrations.DeleteModel(
            name='SubCategory2',
        ),
        migrations.DeleteModel(
            name='SubCategory3',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
