# Generated by Django 5.1.2 on 2024-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_rename_range_name_weightoption_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightoption',
            name='max_weight',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weightoption',
            name='min_weight',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
