# Generated by Django 5.1.2 on 2024-11-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_weightoption_max_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='custom_admin.category')),
                ('metal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.metaltype')),
                ('subcategories', models.ManyToManyField(to='custom_admin.subcategory')),
            ],
        ),
    ]
